name: Testing

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        type: environment
        required: true

env:
  ENVIRONMENT_NAME: ${{ github.event.inputs.environment || 'stage' }}

jobs:
  release:
    name: Build and Push
    environment:
      name: ${{ github.event.inputs.environment || 'stage' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print Deployment Target
        run: |
          echo "Deployment Target: ${{ jobs.release.env.name }}"

      - name: Success Notification
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": ":rocket: Successful Release",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":rocket: Testing (`${{ jobs.release.env.name }}`)"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go to App",
                      "emoji": true
                    },
                    "url": "${{ jobs.release.env.name == 'prod' && 'https://www.google.com' || 'https://www.bing.com' }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
